name: Publicar en Telegram

on:
  schedule:
    - cron: '30 9 * * *'  # Cada día a las 9:30 UTC (~11:30 España)
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  post_to_telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: pip install python-telegram-bot==13.15

    - name: Ejecutar bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHANNEL: ${{ secrets.BOT_CHANNEL }}
      run: python temu_bot.py
